# @package model

# specify the custom model composer by reference
_target_: maze.perception.models.custom_model_composer.CustomModelComposer

# distribution mapping
distribution_mapper_config:
  - action_space: gym.spaces.Box
    distribution: maze.distributions.squashed_gaussian.SquashedGaussianProbabilityDistribution

# policy configuration
policy:
  _target_: maze.perception.models.policies.ProbabilisticPolicyComposer
  networks:
    - _target_: maze_smaac.models.maze_smaac_networks.MazeSMAACPolicyNet
      # parameters:
      dropout: 0
      state_dim: 128
      nheads: 8
  substeps_with_separate_agent_nets: []

# critic configuration
critic:
  _target_: maze.perception.models.critics.StateActionCriticComposer
  networks:
    - _target_: maze_smaac.models.maze_smaac_networks.MazeSMAACStateActionValueNet
      # parameters:
      dropout: 0
      state_dim: 128
      nheads: 8
