name: Maze-SMAAC Build

on: [push]

jobs:

  # Build complete image; run tests; push to Dockerhub.
  build-push:

    runs-on: ubuntu-latest
    steps:

      - name: Free up disk space.
        run: sudo rm -rf "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY" "/usr/share/dotnet/"

      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v1

      - name: Cache layers for image.
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-env-${{ github.sha }}
          restore-keys: buildx-

      - name: Login to DockerHub.
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image with environment.
        uses: docker/build-push-action@v2
        with:
          file: docker/maze_smaac.dockerfile
          build-args: MAZE_CORE_ENV=enliteai/maze:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: enliteai/maze_smaac:latest
          push: true

      - name: Move image caches.
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Output image digest.
        run: echo ${{ steps.docker_build_rllibtf.outputs.digest }}
